/*
 * File: CodeWriter.cs
 * Project: lib
 * Created Date: 28/12/2020
 * Author: Shun Suzuki
 * -----
 * Last Modified: 21/05/2021
 * Modified By: Shun Suzuki (suzuki@hapis.k.u-tokyo.ac.jp)
 * -----
 * Copyright (c) 2020 Hapis Lab. All rights reserved.
 * 
 */

using System;
using System.IO;

namespace autd_wrapper_generator.lib
{
    internal class CodeWriter : IDisposable
    {
        private readonly Parser _parser;
        private readonly StreamWriter _sw;
        private readonly ICodeGenerator _engine;

        public CodeWriter(ICodeGenerator engine, string outputPath)
        {
            _parser = new Parser();
            _sw = new StreamWriter(outputPath);
            _engine = engine;
            _sw.WriteLine($"{_engine.GetCommentPrefix()} This file is generated by autd_wrapper_generator (https://github.com/shinolab/autd-wrapper-generator)");
            _sw.WriteLine(_engine.GetFileHeader());
        }

        public void Write(string headerPath, string libName)
        {
            foreach (var func in _parser.EnumerateFunctions(headerPath)) _sw.WriteLine(_engine.GetFunctionDefinition(func, libName));
        }

        public void Close()
        {
            _sw.WriteLine(_engine.GetFileFooter());
            _sw.Flush();
            _sw.Close();
        }

        public void Dispose()
        {
            _sw?.Dispose();
        }
    }
}
