using System.IO;

namespace autd_wrapper_generator.lib
{
    internal class CodeWriter
    {
        private readonly ICodeGenerator _engine;
        private readonly string _fileName;
        public CodeWriter(ICodeGenerator engine, string fileName)
        {
            _engine = engine;
            _fileName = fileName;
        }

        public void Write(Parser parser)
        {
            using var sw = new StreamWriter(_fileName);
            sw.WriteLine($"{_engine.GetCommentPrefix()} This file is generated by autd_wrapper_generator");
            sw.WriteLine(_engine.GetFileHeader());
            foreach (var func in parser)
                sw.WriteLine(_engine.GetFunctionDefinition(func));
            sw.WriteLine(_engine.GetFileFooter());
        }
    }
}
